### ISSUE TITLE
pypi installation failing on v0.3.1

### ISSUE THREAD

**Issue by pelssers** [JelleAalbers/wimprates#6]
`pip install wimprates` doesn't work since wimprates `0.3.1`. It fails with:
```
FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.md'
```
the file was renamed from `.rst` to `.md` format but somehow PyPI still has the old one.

**Comment by JelleAalbers** [comment]
Oops... forgot to update the MANIFEST.in. I now made a new release, hopefully this one works. 

(Actually pypi still had wimprates 0.2.something until today: we tried to concatenate README and HISTORY then pass the whole thing off as rst, which did not compile on pypi. As a result it rejects the entire upload. This is why the file was reformatted / renamed.)

**Comment by pelssers** [comment]
Thanks! I can now pip install wimprates (v0.3.2) again.
